spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:todo_dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
  flyway:
    baselineOnMigrate: true
    user: ${DB_MIGRATION_USER:postgres}
    password: ${DB_MIGRATION_PASSWORD}